# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"\xbd\x01\n\x0b\x43hatMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x34\n\x08metadata\x18\x05 \x03(\x0b\x32\".chatbot.ChatMessage.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xdb\x01\n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x16\n\x0e\x63lassification\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x35\n\x08metadata\x18\x06 \x03(\x0b\x32#.chatbot.ChatResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"H\n\x12\x43hatHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"|\n\x13\x43hatHistoryResponse\x12&\n\x08messages\x18\x01 \x03(\x0b\x32\x14.chatbot.ChatMessage\x12(\n\tresponses\x18\x02 \x03(\x0b\x32\x15.chatbot.ChatResponse\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x32\xd5\x01\n\x0b\x43hatService\x12:\n\x0bSendMessage\x12\x14.chatbot.ChatMessage\x1a\x15.chatbot.ChatResponse\x12=\n\nChatStream\x12\x14.chatbot.ChatMessage\x1a\x15.chatbot.ChatResponse(\x01\x30\x01\x12K\n\x0eGetChatHistory\x12\x1b.chatbot.ChatHistoryRequest\x1a\x1c.chatbot.ChatHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE_METADATAENTRY']._loaded_options = None
  _globals['_CHATMESSAGE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CHATRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_CHATRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CHATMESSAGE']._serialized_start=27
  _globals['_CHATMESSAGE']._serialized_end=216
  _globals['_CHATMESSAGE_METADATAENTRY']._serialized_start=169
  _globals['_CHATMESSAGE_METADATAENTRY']._serialized_end=216
  _globals['_CHATRESPONSE']._serialized_start=219
  _globals['_CHATRESPONSE']._serialized_end=438
  _globals['_CHATRESPONSE_METADATAENTRY']._serialized_start=169
  _globals['_CHATRESPONSE_METADATAENTRY']._serialized_end=216
  _globals['_CHATHISTORYREQUEST']._serialized_start=440
  _globals['_CHATHISTORYREQUEST']._serialized_end=512
  _globals['_CHATHISTORYRESPONSE']._serialized_start=514
  _globals['_CHATHISTORYRESPONSE']._serialized_end=638
  _globals['_CHATSERVICE']._serialized_start=641
  _globals['_CHATSERVICE']._serialized_end=854
# @@protoc_insertion_point(module_scope)
